"""Request/response metrics logging middleware.

Tasks.md reference:
- T056: Add request/response metrics logging in backend/app/middleware/

This middleware logs method, path, status code, and latency.
"""

import logging
import time
from collections.abc import Awaitable, Callable

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response

logger = logging.getLogger(__name__)


class MetricsLoggingMiddleware(BaseHTTPMiddleware):
    """Log basic request/response metrics."""

    async def dispatch(
        self,
        request: Request,
        call_next: Callable[[Request], Awaitable[Response]],
    ) -> Response:
        """Dispatch a request and log basic metrics.

        Args:
            request: Incoming HTTP request.
            call_next: Next middleware/app callable.

        Returns:
            The response generated by the downstream app.
        """
        start = time.perf_counter()
        response = await call_next(request)
        duration_ms = (time.perf_counter() - start) * 1000

        logger.info(
            "request method=%s path=%s status=%s duration_ms=%.2f",
            request.method,
            request.url.path,
            response.status_code,
            duration_ms,
        )

        return response
